FROM python:3-slim

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ARG PAIRS_ARE_PUBLIC=False
ARG LOOKBACK_DAYS=28
ARG MAGICAL_TEXT="This weeks random coffees are"
ARG CHAN_NAMES_ARE_IDS=False

ENV PAIRS_ARE_PUBLIC=${PAIRS_ARE_PUBLIC}
ENV LOOKBACK_DAYS=${LOOKBACK_DAYS}
ENV MAGICAL_TEXT=${MAGICAL_TEXT}
ENV CHAN_NAMES_ARE_IDS=${CHAN_NAMES_ARE_IDS}

ENV SLACK_API_TOKEN="xoxb-XXXXXXXXXXXXX-XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXX"
ENV CHANNEL_NAME="random-coffee"
ENV PRIVATE_CHANNEL_NAME_FOR_MEMORY="randomcoffebotprivatechannelformemory"

COPY ./src/*.py .

CMD [ "python", "/app/main.py" ]
